'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabase';
import {useRouter} from 'next/navigation';
import Brand from '../components/Brand';
const catalog={'Verduras':['Jitomate','Cebolla','Papa','Zanahoria','Calabacita','Chayote','Pepino','Lechuga','Brócoli','Coliflor','Chile','Cilantro','Perejil','Espinaca','Apio','Ajo','Elote'],'Frutas':['Manzana','Plátano','Naranja','Mandarina','Limón','Aguacate','Papaya','Piña','Mango','Uvas','Fresas','Sandía','Melón','Arándanos','Zarzamora','Frambuesa','Pera'],'Cremería, huevo y tortillas':['Jamón','Queso panela','Queso Oaxaca','Queso manchego','Crema','Yogurt','Mantequilla','Huevo','Tortillas']};
const icons={'Verduras':'🥦','Frutas':'🍎','Cremería, huevo y tortillas':'🧀'};const units=['kg','g','piezas','litros','ml','paquetes','docenas'];const blank=(product='')=>({product,qty:'',unit:'kg',variety:'',features:'',brand:''});
export default function Home(){const router=useRouter();const initial=useMemo(()=>Object.fromEntries(Object.entries(catalog).map(([c,ps])=>[c,ps.map(p=>blank(p))])),[]);const[data,setData]=useState(initial);const[others,setOthers]=useState([blank()]);const[summary,setSummary]=useState('');const[msg,setMsg]=useState('');const[sending,setSending]=useState(false);const[name,setName]=useState('');
 useEffect(()=>{(async()=>{const{data:u}=await supabase.auth.getUser();if(u.user){const{data:p}=await supabase.from('profiles').select('first_name').eq('id',u.user.id).maybeSingle();setName(p?.first_name||'')}})();try{const base=JSON.parse(sessionStorage.getItem('mandadoBase')||'null');if(base){applyBase(base);sessionStorage.removeItem('mandadoBase');return}const pending=JSON.parse(sessionStorage.getItem('mandadoPendiente')||'null');if(pending){setData(pending.data||initial);setOthers(pending.others?.length?pending.others:[blank()]);sessionStorage.removeItem('mandadoPendiente')}}catch{}},[initial]);
 const applyBase=(base)=>{const next=structuredClone(initial),extra=[];for(const it of base||[]){const n=it.custom_product||it.product_name||it.product||'';let found=false;for(const cat of Object.keys(next)){const i=next[cat].findIndex(r=>r.product===n);if(i>=0){next[cat][i]={...next[cat][i],qty:String(it.quantity??it.qty??''),unit:it.unit||'kg',variety:it.variety||'',features:it.features||'',brand:it.brand_presentation||it.brand||''};found=true;break}}if(!found&&n)extra.push({product:n,qty:String(it.quantity??it.qty??''),unit:it.unit||'kg',variety:it.variety||'',features:it.features||'',brand:it.brand_presentation||it.brand||''})}setData(next);if(extra.length)setOthers(extra)};
 const update=(cat,i,k,v)=>setData(d=>({...d,[cat]:d[cat].map((r,n)=>n===i?{...r,[k]:v}:r)}));const updateOther=(i,k,v)=>setOthers(a=>a.map((r,n)=>n===i?{...r,[k]:v}:r));const selected=[...Object.values(data).flat(),...others].filter(r=>r.product&&Number(r.qty)>0);
 const review=()=>setSummary(selected.length?selected.map((r,i)=>`${i+1}. ${r.product} — ${r.qty} ${r.unit}${r.variety?' · '+r.variety:''}${r.features?' · '+r.features:''}${r.brand?' · '+r.brand:''}`).join('\n'):'Aún no has agregado cantidades.');
 const send=async()=>{if(sending)return;setMsg('');if(!selected.length){setMsg('Agrega al menos un producto.');return}setSending(true);try{const{data:u}=await supabase.auth.getUser();if(!u.user){sessionStorage.setItem('mandadoPendiente',JSON.stringify({data,others}));router.push('/login');return}const{data:a}=await supabase.from('addresses').select('id').eq('user_id',u.user.id).maybeSingle();if(!a){sessionStorage.setItem('mandadoPendiente',JSON.stringify({data,others}));router.push('/cuenta');return}const{data:o,error}=await supabase.from('orders').insert({user_id:u.user.id,address_id:a.id,status:'recibido',submitted_at:new Date().toISOString()}).select('id,folio').single();if(error)throw error;const items=selected.map(r=>({order_id:o.id,custom_product:r.product,quantity:Number(r.qty),unit:r.unit,variety:r.variety||null,features:r.features||null,brand_presentation:r.brand||null}));const{error:ie}=await supabase.from('order_items').insert(items);if(ie){await supabase.from('orders').delete().eq('id',o.id);throw ie}router.push(`/pedidos/${o.id}`)}catch(e){setMsg(e?.message||'No pudimos enviar el pedido.')}finally{setSending(false)}};
 return <main className="wrap"><section className="hero"><Brand/><div className="loginHero"><span className="eyebrow">Pedidos hasta sábado · Entrega domingo</span><h1 className="welcome">{name?`Hola, ${name} 👋`:'Tu mandado, fácil y rápido'}</h1><p className="sub">Elige lo que necesitas. No mostramos precios porque se cobra el costo real de la compra más el servicio.</p><button className="cta" onClick={()=>document.getElementById('catalogo')?.scrollIntoView({behavior:'smooth'})}>🛒 Hacer nuevo mandado</button></div></section><section className="quickGrid mt"><button className="quickCard" onClick={()=>router.push('/pedidos')}><span className="emoji">📋</span><strong>Mis pedidos</strong></button><button className="quickCard" onClick={()=>router.push('/lista-habitual')}><span className="emoji">❤️</span><strong>Mi lista habitual</strong></button><button className="quickCard" onClick={()=>router.push('/pedidos')}><span className="emoji">🔄</span><strong>Repetir pedido</strong></button><button className="quickCard" onClick={()=>router.push('/cuenta')}><span className="emoji">👤</span><strong>Mi perfil</strong></button></section>
 <div id="catalogo">{Object.entries(data).map(([cat,rows])=><section className="card mt" key={cat}><h2 className="sectionTitle"><span>{icons[cat]}</span>{cat}</h2><div className="productGrid">{rows.map((r,i)=><div className="productCard" key={r.product}><div className="productName">{r.product}</div><div className="fields"><input value={r.qty} inputMode="decimal" onChange={e=>update(cat,i,'qty',e.target.value)} placeholder="Cantidad"/><select value={r.unit} onChange={e=>update(cat,i,'unit',e.target.value)}>{units.map(u=><option key={u}>{u}</option>)}</select><input className="wide" value={r.variety} onChange={e=>update(cat,i,'variety',e.target.value)} placeholder="Tipo / variedad (opcional)"/><input className="wide" value={r.features} onChange={e=>update(cat,i,'features',e.target.value)} placeholder="Características / marca (opcional)"/></div></div>)}</div></section>)}</div>
 <section className="card mt"><h2 className="sectionTitle">➕ Otros</h2>{others.map((r,i)=><div className="productCard mt" key={i}><div className="fields"><input className="wide" value={r.product} onChange={e=>updateOther(i,'product',e.target.value)} placeholder="Producto"/><input value={r.qty} inputMode="decimal" onChange={e=>updateOther(i,'qty',e.target.value)} placeholder="Cantidad"/><select value={r.unit} onChange={e=>updateOther(i,'unit',e.target.value)}>{units.map(u=><option key={u}>{u}</option>)}</select><input className="wide" value={r.variety} onChange={e=>updateOther(i,'variety',e.target.value)} placeholder="Tipo / variedad"/><input className="wide" value={r.features} onChange={e=>updateOther(i,'features',e.target.value)} placeholder="Características / marca"/></div></div>)}<div className="actions"><button className="btn secondary" onClick={()=>setOthers(a=>[...a,blank()])}>+ Agregar otro producto</button></div></section>
 <section className="card mt"><h2>Revisar mi mandado</h2><p className="sub">{selected.length} producto{selected.length===1?'':'s'} seleccionado{selected.length===1?'':'s'}.</p><div className="actions"><button className="btn secondary" onClick={review}>Ver resumen</button><button className="btn primary" disabled={sending} onClick={send}>{sending?'Enviando…':'Enviar mandado →'}</button></div>{summary&&<div className="summary">{summary}</div>}{msg&&<p className="notice">{msg}</p>}</section><nav className="bottomNav"><button onClick={()=>router.push('/')}><span>⌂</span>Inicio</button><button onClick={()=>router.push('/pedidos')}><span>▣</span>Pedidos</button><button onClick={()=>router.push('/lista-habitual')}><span>♡</span>Habitual</button><button onClick={()=>router.push('/cuenta')}><span>♙</span>Perfil</button></nav></main>}
